Исключение catch Throwable нужно поставить последним, поскольку она самое глобальное и не даст обработать
 стоящие ниже его по йерархии исключения NullPointerException и IndexOutOfBoundsException. 
 а в данной задаче наша ошибка должна обработаться IndexOutOfBoundsException. поскольку у массива 
 длина 2, а мы обращаемся к индексу 3.